# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Q7mqX9MaYmdWaos9ZDZczwouMqQ-uCq
"""

import pickle
import streamlit as st
import pandas as pd

# Load the machine learning model from the pickle file
with open('Sarcopenia_Model_SF.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

# Define function to collect user input and make predictions
def predict_sarcopenia(user_input):
    # Create a DataFrame with the user input
    input_data = pd.DataFrame(user_input, index=[0])

    # Ensure that the input data matches the format used during training (e.g., scaling)

    # Make predictions using the loaded model
    predictions = loaded_model.predict(input_data)
    return predictions[0]

# Streamlit app
st.title("Sarcopenia Prediction App")

# Collect user input for four features
user_input = {}
feature_names = ['GS_1','Gender_encoded','CST','Star']


for feature_name in feature_names:
    user_input[feature_name] = st.number_input(f"Enter {feature_name}:", step=0.01)

# Make predictions when the user clicks the "Predict" button
if st.button("Predict"):
    sarcopenia_prediction = predict_sarcopenia(user_input)
    if sarcopenia_prediction == 0:
      st.markdown("<h3 style='color: blue;'>The model forecasts that the patient will not receive a diagnosis of Sarcopenia</h1>",unsafe_allow_html=True)
    else:
      st.markdown("<h3 style='color: orange;'>The model forecasts that the patient will receive a diagnosis of Sarcopenia</h1>",unsafe_allow_html=True)


# Optionally, you can display additional information or visualizations here

